# Generated by Django 6.0.3 on 2026-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='default.jpg', upload_to='profile_image/'),
        ),
    ]
