# Generated by Django 6.0.3 on 2026-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='default.jpg', upload_to='userprofile/media/profile_image/'),
        ),
    ]
