# Generated by Django 6.0.3 on 2026-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='userprofile/profile_image/default.jpg', upload_to='userprofile/profile_image/'),
        ),
    ]
