# Generated by Django 6.0.3 on 2026-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='userprofile/default.jpg', upload_to='userprofile/profile_image/'),
        ),
    ]
