# Generated by Django 6.0.3 on 2026-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Book'},
        ),
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='image_book/'),
        ),
    ]
