# Generated by Django 6.0.3 on 2026-03-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_book_image_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
