# Generated by Django 6.0.3 on 2026-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='book/image_book/'),
        ),
    ]
