# Generated by Django 6.0.3 on 2026-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name_plural': 'Password Reset'},
        ),
    ]
